context:
  name: d2
  version: "0.6.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - target_directory: src
    url: https://github.com/terrastruct/d2/archive/refs/tags/v${{ version }}.tar.gz
    sha256: ddb6210b927e62c0111cb9a9f7320010df8b89bf6a24f73d6012f6d4e477f27c
  - url: https://raw.githubusercontent.com/golang/freetype/refs/heads/master/LICENSE
    sha256: d3ba056adc2b7909e95681deaae397fb37c97ed491a920f491214f07b62c41d0
    file_name: freetype-licence.txt
  - url: https://github.com/golang/freetype/raw/refs/heads/master/licenses/ftl.txt
    sha256: f4b133e25df1f86ad3ffea453aa0e613f0474f34778dbbb3e437e7b2724937d8
    file_name: freetype-licence-ftl.txt
  - url: https://github.com/golang/freetype/raw/refs/heads/master/licenses/gpl.txt
    sha256: c4120c6752c910c299e3bd9cb3a46ff262c268303ca2069b61f92f10a5656c18
    file_name: freetype-licence-gpl.txt


build:
  number: 0

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - ${{ stdlib("c") }}
    - go-licenses


tests:
  - script:
      - d2 --help

about:
  homepage: https://github.com/terrastruct/d2
  summary: D2 is a modern diagram scripting language that turns text to diagrams.
  license: MPL-2.0 AND (GPL-2.0-or-later OR LicenseRef-FreeType)
  license_file:
    - src/LICENSE.txt
    - library_licenses
    - freetype-license.txt
    - freetype-license-ftl.txt
    - freetype-license-gpl.txt

extra:
  recipe-maintainers:
    - moritzwilksch
